- name: Clone k-bench repository
  git:
    repo: https://github.com/vmware-tanzu/k-bench.git
    dest: ~{{ ansible_user }}/.k-bench
    version: master  # You can specify a branch or tag here
  register: git_clone_result

- name: Change directory to k-bench
  shell: cd ~{{ ansible_user }}/.k-bench
  args:
    executable: /bin/bash
  when: git_clone_result.changed  # Only change directory if the repository was cloned

- name: Run k-bench install script
  shell: sudo ./install.sh
  args:
    chdir: ~{{ ansible_user }}/.k-bench
  when: git_clone_result.changed  # Only run the script if the repository was cloned

# Add more test_name entries as needed
- name: List of test names
  set_fact:
    test_names: ["cp_light_1client", "cp_heavy_8client", "cp_heavy_12client", "dp_redis_density"]  # Add more test names as needed

- name: Create config paths
  file:
    path: "~{{ ansible_user }}/.k-bench/configs/{{ item }}"
    state: directory
  loop: "{{ test_names }}"
  # when: "'master' in inventory_hostname"

- name: Copy configuration files
  ansible.builtin.copy:
    src: "../etc/{{ item }}/"
    dest: "~{{ ansible_user }}/.k-bench/configs/{{ item }}/" # TODO: extend to copy everything under {{item}}
    directory_mode: yes
  loop: "{{ test_names }}"
  # when: "'master' in inventory_hostname"