---
- name: Disable apparmor
  shell: |
    sudo systemctl stop apparmor && sudo systemctl disable apparmor

- name: "Restart containerd service"
  become: true
  systemd:
    name: containerd
    daemon_reload: yes
    state: restarted

- name: Check the join_cluster script availability
  ansible.builtin.stat:
    path: /tmp/join_cluster.sh
  register: file_result

- name: Copy the cluster joining script
  when: not file_result.stat.exists
  ansible.builtin.copy:
    src: "../.kube/{{k8s_distribution}}-join_cluster.sh"
    dest: /tmp/join_cluster.sh
    mode: '755'

- name: Join k8s cluster
  ansible.builtin.shell: |
    sh /tmp/join_cluster.sh
    sleep 30
  register: cluster_join
  changed_when: true

- name: Check result for cluster
  ansible.builtin.debug:
    msg: "Node {{ ansible_host }} has {{ 'joined the cluster.' if cluster_join.rc == 0 else 'failed to join the cluster.' }} "