---
- name: Copy the cluster cleaning up script
  ansible.builtin.copy:
    src: "../../etc/cleanup-v2.sh"
    dest: /tmp/cleanup.sh
    mode: '755'

- name: Clean the cluster
  ansible.builtin.shell: |
    sh /tmp/cleanup.sh

- name: Reboot all nodes.
  reboot:
    post_reboot_delay: 60
    reboot_timeout: 80
    connect_timeout: 300
    test_command: uptime

