---

- name: Disable k0s service
  systemd:
    name: "{{ item }}"
    state: stopped
    enabled: no
  failed_when: false
  with_items:
    - k0scontroller
    - k0sworker

- name: run k0s stop
  command: sudo k0s stop
  ignore_errors: true

- name: run k0s reset
  command: k0s reset

- name: Umount k0s filesystems
  include_tasks: umount_with_children.yml
  with_items:
    - "{{ k0s_data_dir }}"
    - "{{ k0s_libexec_dir }}"
  loop_control:
    loop_var: mounted_fs

- name: Remove k0s Directories and binary
  become: true
  file:
    path: "{{ item }}"
    state: absent
  loop:
    - "{{ k0s_config_dir }}"
    - "{{ k0s_data_dir }}"
    - "{{ k0s_libexec_dir }}"
    - /var/lib/kubelet
    - "{{ systemd_dest }}/k0scontroller.service"
    - "{{ systemd_dest }}/k0sworker.service"
    - "{{k0s_binary_dest}}"

- name: daemon_reload
  systemd:
    daemon_reload: yes
