Vagrant.configure("2") do |config|
    # Loop to create 6 machines
    (1..2).each do |i|
      config.vm.define "machine#{i}" do |machine|
        machine.vm.box = "hashicorp/bionic64"
        config.vm.box_version = "1.0.282"
        machine.vm.hostname = "machine#{i}"
        machine.vm.network "private_network", ip: "192.168.10.#{10+i}"
        machine.vm.provider "virtualbox" do |vb|
          vb.memory = "256"
        end
        machine.vm.provision "shell", inline: <<-SHELL
          # # Update package repositories
          # sudo apt-get update

          # # Install dependencies
          # sudo apt-get install -y unzip

          # # Download and install Terraform
          # wget https://releases.hashicorp.com/terraform/0.15.5/terraform_0.15.5_linux_amd64.zip
          # unzip terraform_0.15.5_linux_amd64.zip
          # sudo mv terraform /usr/local/bin/

          # # Clean up downloaded files
          # rm terraform_0.15.5_linux_amd64.zip
        SHELL
      end
    end
  end