---
- hosts: all
  tasks:
    - name: Check if machine is a Raspberry Pi
      shell: "cat /proc/cpuinfo | grep 'Raspberry Pi'"
      register: rpi_check
      failed_when: false
      changed_when: false

    - name: Set fact if it's a Raspberry Pi
      set_fact:
        is_rpi: "{{ rpi_check.stdout != '' }}"
        
    - name: Display PI nodes
      debug:
        msg: "{{ ansible_host }} is a common node"
      when: is_rpi

    - name: Display master node
      debug:
        msg: "{{ ansible_host }} is a master node"
      when: is_rpi != true

    - name: Check if MongoDB is installed
      command: "which mongod"
      register: mongodb_check
      failed_when: false
      changed_when: false

    - name: Set fact if MongoDB is installed
      set_fact:
        has_mongodb: "{{ mongodb_check.rc == 0 }}"

    - name: Display sidecar node
      debug:
        msg: "{{ ansible_host }} is a sidecar node"
      when: has_mongodb