---
- name: Run k-bench benchmark
  hosts: master
  become: true

  tasks:
    # Add more test_name entries as needed
    - name: List of test names
      set_fact:
        # test_names: ["cp_light_1client", "cp_heavy_8client", "cp_heavy_12client", "dp_redis_density"]  # Add more test names as needed
        test_names: ["cp_heavy_12client"]
      
    - name: Create config paths
      file:
        path: "~{{ ansible_user }}/.k-bench/test-results/{{ item }}/{{ tag }}"
        state: directory
      loop: "{{ test_names }}"

    - name: Get before Date and Time
      command:  date '+%s'
      register: before_datetime
      
    - name: Display the time before test
      debug:
        var: before_datetime.stdout

    - name: Run kbench command
      command: kbench -benchconfig "/home/{{ ansible_user }}/.k-bench/configs/{{ item }}/config.json" -outdir "/home/{{ ansible_user }}/.k-bench/test-results/{{ item }}" -kubeconfig "/home/{{ ansible_user }}/.kube/config"
      loop: "{{ test_names }}"

    - name: Get after Date and Time
      command:  date '+%s'
      register: after_datetime
      
    - name: Display the time before test
      debug:
        var: after_datetime.stdout

    # - name: Create local directory for test results for {{k8s_distribution}}}
    #   ansible.builtin.file:
    #     path: ../../k-bench-results/{{k8s_distribution}}/{{ item }}/
    #     state: directory
    #   loop: "{{ test_names }}"
        
    - name: Copy test results to repository
      fetch:
        src: "/home/{{ ansible_user }}/.k-bench/test-results/{{ item }}/kbench.log"
        dest: "../../k-bench-results/{{k8s_distribution}}/{{ item }}/ {{ tag }}/"
        flat: yes
      loop: "{{ test_names }}"
    
    - name: Delete test results on a remote machine
      file:
        path: "/home/{{ ansible_user }}/.k-bench/test-results/{{ item }}/kbench.log"
        state: absent
      loop: "{{ test_names }}"