---
- name: Run k-bench benchmark
  hosts: master
  become: true

  tasks:
    # Add more test_name entries as needed
    # - name: List of test names
    #   set_fact:
    #     # test_names: ["cp_light_1client", "cp_heavy_8client", "cp_heavy_12client", "dp_redis_density"]  # Add more test names as needed
    #     test_names: ["dp_redis_density"]
      
    - name: Create config paths
      file:
        path: "~{{ ansible_user }}/.k-bench/test-results/{{ test_type }}/{{ tag }}"
        state: directory

    - name: Get before Date and Time
      command:  date '+%s'
      register: before_datetime
      
    - name: Display the time before test
      debug:
        var: before_datetime.stdout

    - name: Write variable to file
      copy:
        content: "{{ before_datetime.stdout }}"
        dest: "./tmp-before.txt"

    - name: Copy before time
      fetch:
        src: "/home/{{ ansible_user }}/tmp-before.txt"
        dest: "./"
        flat: yes

    - name: Run kbench command
      command: kbench -benchconfig "/home/{{ ansible_user }}/.k-bench/configs/{{ test_type }}/config.json" -outdir "/home/{{ ansible_user }}/.k-bench/test-results/{{ test_type }}" -kubeconfig "/home/{{ ansible_user }}/.kube/config"

    - name: Get after Date and Time
      command:  date '+%s'
      register: after_datetime
      
    - name: Display the time before test
      debug:
        var: after_datetime.stdout

    - name: Write variable to file
      copy:
        content: "{{ after_datetime.stdout }}"
        dest: "./tmp-after.txt"

    - name: Copy after time
      fetch:
        src: "/home/{{ ansible_user }}/tmp-after.txt"
        dest: "./"
        flat: yes

    # - name: Create local directory for test results for {{k8s_distribution}}}
    #   ansible.builtin.file:
    #     path: ../../k-bench-results/{{k8s_distribution}}/{{ test_type }}/
    #     state: directory
    #   loop: "{{ test_names }}"
        
    - name: Copy test results to repository
      fetch:
        src: "/home/{{ ansible_user }}/.k-bench/test-results/{{ test_type }}/kbench.log"
        dest: "../../k-bench-results/{{k8s_distribution}}/{{ test_type }}/{{ tag }}/"
        flat: yes
    
    - name: Delete test results on a remote machine
      file:
        path: "/home/{{ ansible_user }}/.k-bench/test-results/{{ test_type }}/kbench.log"
        state: absent