---
- name: Run k-bench benchmark
  hosts: master
  become: true

  tasks:
    # Add more test_name entries as needed
    - name: List of test names
      set_fact:
        test_names: ["cp_light_1client"]  # Add more test names as needed
      
    - name: Create config paths
      file:
        path: "~{{ ansible_user }}/.k-bench/test-results/{{ item }}"
        state: directory
      loop: "{{ test_names }}"

    - name: Run kbench command
      command: kbench -benchconfig "/home/{{ ansible_user }}/.k-bench/configs/{{ item }}/config.json" -outdir "/home/{{ ansible_user }}/.k-bench/test-results/{{ item }}" -kubeconfig "/home/{{ ansible_user }}/.kube/config"
      loop: "{{ test_names }}"
      async: 3600
      poll: 0