- name: k3s cluster setup
  hosts: iot_cluster
  gather_facts: true
  become: true
  roles:
    - role: k3s/prereq
    - role: k3s/download
    - role: k3s/raspberrypi

- hosts: master
  become: true
  roles:
    - role: k3s/master

- hosts: node
  become: true
  roles:
    - role: k3s/node