# reference: https://github.com/akshaygholap45/k8s-vm-cluster
---
- name: Deploy common packages
  hosts: master:node
  become: true
  roles:
    - k8s/commons
    - k8s/configure-kernel
    - k8s/containerd

- name: Setup Control Plane
  hosts: master
  become: true
  roles:
    - k8s/cluster-setup
  tags: master_check

- name: Join cluster
  hosts: node
  become: true
  roles:
    - k8s/worker-setup
