- name: monitoring setup
  hosts: iot_cluster
  gather_facts: true
  vars_files:
    - "../roles/netdata/vars/main.yml"
  become: true
  roles:
    - role: netdata


# TODO DEFINE IT LATER
# - name: sidecar setting up (mongodb)
#   hosts: sidecar
#   become: true
#   tasks: