- name: setuping netdata tags
  hosts: iot_cluster
  gather_facts: true
  become: true

  tasks:
    - name: change the tag to {{tag}}
      ansible.builtin.lineinfile:
        path: /etc/netdata/netdata.conf
        regexp: '^\s*tag\s*=\s*.*$'
        line: '    tag = {{ tag }}'

        
    - name: Restart Netdata
      ansible.builtin.service:
        name: netdata       # Make sure this matches the actual service name
        state: restarted    # This is the action you want to perform
    # this type of reload sometimes does not work
    # - name: reload labels
    #   command: netdatacli reload-labels
